name: Master Build

on: 
  push:
    branches:
      - master

jobs:

  test-win:
    name: Testing Windows

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Run dotnet tests
      run: |
        cd src
        dotnet test

    - name: Run example dotnet tests
      run: |
        cd examples/nuget-usage
        dotnet test

  test-linux:
    name: Test Linux

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Run dotnet tests
      run: |
        cd src
        dotnet test

    - name: Run example dotnet tests
      run: |
        cd examples/nuget-usage
        dotnet test

  test-osx:
    name: Test MacOS

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Run dotnet tests
      run: |
        cd src
        dotnet test

    - name: Run example dotnet tests
      run: |
        brew install mono-libgdiplus
        cd examples/nuget-usage
        dotnet test